# Generated by Django 2.2.3 on 2019-07-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('server_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('server_windows_authentication', models.CharField(max_length=255)),
                ('licence_key', models.CharField(max_length=255)),
                ('activate_day', models.DateTimeField(max_length=255)),
                ('expire_day', models.DateTimeField(max_length=255)),
                ('allowed_users', models.IntegerField(max_length=255)),
                ('installed_users', models.IntegerField(max_length=255)),
                ('windows_username', models.CharField(max_length=255)),
                ('windows_password', models.CharField(max_length=255)),
                ('company_phone', models.IntegerField(max_length=255)),
            ],
        ),
    ]
