# Generated by Django 2.2.3 on 2019-07-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credentials',
            options={'ordering': ('company_code',)},
        ),
    ]
